#pragma config(Sensor, dgtl1,  bumper,         sensorTouch)
#pragma config(Motor,  port1,           motor1,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           motor2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           motor3,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           motor4,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           servo,         tmotorServoStandard, openLoop)
#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
bool running = true;
string credits1 = "By Crow, Bridge,";
string credits2 = "& AA. To /zero.";
// Code Refactoring by Wolf


/*
7 = Controls initial modes l=1,U=2,R=3, then 8 to change mode, leave it alone for ~10 sec, setting 1

*/

// You may ask why this is an int... This is because this will allow for error reporting as shown below:
/*
if (errorcondition)
{
  return 5
}
*/

int mode1()
{
	motor[motor2] = vexRT[Ch3];
	motor[motor1] = vexRT[Ch2];
	motor[motor4] = vexRT[Ch3Xmtr2];
	motor[motor3] = vexRT[Ch2Xmtr2];
	return 0;
}

int mode2()
{
	motor[motor3] = vexRT[Ch3];
	motor[motor4] = vexRT[Ch3];
	motor[motor1] = vexRT[Ch2];
	motor[motor2] = vexRT[Ch2];
	return 0;
}

int mode3()
{
	motor[motor2] = vexRT[Ch3];
	motor[motor1] = vexRT[Ch2];
	motor[motor3] = vexRT[Ch3Xmtr2];
	motor[motor4] = vexRT[Ch3Xmtr2];
	return 0;
}

task main()
{
	int mode1button = Btn7L;
	int mode2button = Btn7U;
	int mode3button = Btn7R;
	int restartbutton = Btn7D;
	clearTimer(T1); // Why weren't timers used in the first place? You can clean up so many kludges with this...
	clearLCDLine(0);
	clearLCDLine(1);
	displayLCDPos(0, 0);
	displayNextLCDString(credits1);
	displayLCDPos(1, 0);
	displayNextLCDString(credits2);
	// Opening code. Timer starts at 0, counts up to 10000 mSec. Default is mode 1, unless selected otherwise.
	int mode = 1;
	while (time1[T1] <= 10000)
	{
		if(vexRT[mode1button])
		{
			mode = 1;
			break;
		}
		else if(vexRT[mode2button])
		{
			mode = 2;
			break;
		}
		else if (vexRT[mode3button])
		{
			mode = 3;
			break;
		}
	}
	while(true)
	{
		if(running)
		{
			if (mode == 1)
			{
				mode1();
			}
			else if (mode == 2)
			{
				mode2();
			}
			else if (mode == 3)
			{
				mode3();
			}
			if (vexRT[mode1button])
			{
				mode = 1;
			}
			else if (vexRT[mode2button])
			{
				mode = 2;
			}
			else if (vexRT[mode3button])
			{
				mode = 3;
			}
			if (SensorValue[bumper] == 1)
			{
				running = false;
			}
		}
		else
		{
			if (vexRT[restartbutton])
			{
				motor[motor1] = 0;
				motor[motor2] = 0;
				motor[motor3] = 0;
				motor[motor4] = 0;
				running = true;
			}
		}
	}
}
