#pragma config(Motor,  port1,           rightBaseOne,  tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightBaseTwo,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightBaseThree, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightTopLift,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rightBottomLift, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftTopLift,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftBottomLift, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           leftBaseThree, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           leftBaseTwo,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          leftBaseOne,   tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "common.c"

// Definitions to make the code more readable when referencing
// an assembly on the robot
#define LeftBase leftBaseTwo // The main left base motor.
#define RightBase rightBaseTwo // The main right base motor.
#define Lift rightTopLift // A lift motor.

void setupMotors() {
	// Set up all the motors for the robot.
	// This includes slaving together multiple physical motor
	// mechanisms from the robot together

	// Slave the right side together
	slaveMotor(rightBaseOne, rightBaseTwo);
	slaveMotor(rightBaseThree, rightBaseTwo);

	// Slave the left side together
	slaveMotor(leftBaseOne, leftBaseTwo);
	slaveMotor(leftBaseThree, leftBaseTwo);

	// Slave the lift assembly together
	slaveMotor(rightBottomLift, rightTopLift);
	slaveMotor(leftTopLift, rightTopLift);
	slaveMotor(leftBottomLift, rightTopLift);
}

task main()
{
	setupMotors();
	while (true) {
		motor[LeftBase] = getValueOf(Ch3);
		motor[RightBase] = getValueOf(Ch2);
		motor[Lift] = btnValueOf(Btn5);
	}
}
